esphome:
  name: esp32-c6-climate-and-presence
  friendly_name: Multisensor

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:
  #evel: WARN

# Enable Home Assistant API
api:
  encryption:
    key: "Key"

ota:
  - platform: esphome
    password: "Password"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # power_save_mode: none
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-C6-Climate-And-Presence"
    password: "Password"

captive_portal:

# Get time
time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Stockholm
    servers:
     - 0.pool.ntp.org
     - 1.pool.ntp.org
     - 2.pool.ntp.org
    
web_server:
  port: 80
    
uart:
  id: ld2420_uart
  tx_pin: GPIO0
  rx_pin: GPIO1
  baud_rate: 115200
  data_bits: 8
  stop_bits: 1
  parity: NONE

i2c:
  sda: GPIO2
  scl: GPIO3
  scan: false
  id: bus_a
    
# The LD2420 has 16 sense gates 0-15 and each gate detects 0.7 meters 15th gate = 9m
ld2420:

bme68x_bsec2_i2c:
  address: 0x77
  model: bme680
  operating_age: 28d
  sample_rate: LP
  supply_voltage: 3.3V
  temperature_offset: 4.5

text_sensor:
  - platform: ld2420
    fw_version:
      name: LD2420 Firmware

  - platform: bme68x_bsec2
    iaq_accuracy:
      name: "BME68x IAQ Accuracy"
      
  - platform: template
    name: "BME68x IAQ Classification"
    lambda: |-
      if ( int(id(iaq).state) <= 50) {
        return {"Utmärkt"};
      }
      else if (int(id(iaq).state) >= 51 && int(id(iaq).state) <= 100) {
        return {"Bra"};
      }
      else if (int(id(iaq).state) >= 101 && int(id(iaq).state) <= 150) {
        return {"Lätt förorenad"};
      }
      else if (int(id(iaq).state) >= 151 && int(id(iaq).state) <= 200) {
        return {"Förorenad"};
      }
      else if (int(id(iaq).state) >= 201 && int(id(iaq).state) <= 250) {
        return {"Mycket förorenad"};
      }
      else if (int(id(iaq).state) >= 251 && int(id(iaq).state) <= 350) {
        return {"Allvarligt förorenad"};
      }
      else if (int(id(iaq).state) >= 351) {
        return {"Extremt förorenad"};
      }
      else {
        return {"error"};
      }

  - platform: template
    name: Uptime
    update_interval: 1s
    icon: mdi:clock-start
    lambda: |-
      auto s = millis() / 1000;
      return str_snprintf("%02d:%02d:%02d:%02d", 11, s / 86400, s / 3600 % 24, s / 60 % 60, s % 60);

  - platform: version
    name: ESPHome Version
    hide_timestamp: true
  - platform: wifi_info
    ip_address:
      name: WiFi IP
      icon: mdi:ip-network
    ssid:
      name: WiFi SSID
      icon: mdi:wifi
    mac_address:
      name: "WiFi MAC"
      icon: mdi:identifier
    
sensor:
  - platform: ld2420
    moving_distance:
      name : Moving Distance

  - platform: bh1750
    name: "BH1750 Illuminance"
    address: 0x23
    update_interval: 10s
    
  - platform: bme68x_bsec2
    temperature:
      name: "BME68x Temperature"
    pressure:
      name: "BME68x Pressure"
    humidity:
      name: "BME68x Humidity"
    iaq:
      name: "BME68x IAQ"
      id: iaq
    co2_equivalent:
      name: "BME68x CO2 Equivalent"
    breath_voc_equivalent:
      name: "BME68x Breath VOC Equivalent"
      
  # Reports the WiFi signal strength/RSSI in dB
  - platform: wifi_signal 
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
  
  # Reports the WiFi signal strength in %
  - platform: copy 
    source_id: wifi_signal_db
    name: "WiFi Signal Strength"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: " %"
    entity_category: "diagnostic"
    
  # Only on esp32 
  - platform: internal_temperature
    name: "Internal Temperature"
    
  - platform: uptime
    id: uptime_sec

binary_sensor:
  - platform: ld2420
    has_target:
      name: Presence

switch:
  - platform: shutdown
    name: "Shutdown unit"

  - platform: restart
    name: "Restart unit"

select:
  - platform: ld2420
    operating_mode:
      name: Operating Mode

number:
  - platform: ld2420
    presence_timeout:
      name: Detection Presence Timeout # How long before the sensor is set to cleared after last detection
    min_gate_distance:
      name: Detection Gate Minimum
    max_gate_distance:
      name: Detection Gate Maximum


    gate_move_sensitivity:
      name: Calibration Move Sensitivity Factor
    gate_still_sensitivity:
      name: Calibration Still Sensitivity Factor
    gate_0:                                        # 0-0.7m
      move_threshold:
        name: Gate 0 Move Threshold
      still_threshold:
        name: Gate 0 Still Threshold
    gate_1:                                         #0.7-1.4m
      move_threshold:
        name: Gate 1 Move Threshold
      still_threshold:
        name: Gate 1 Still Threshold
    gate_2:                                         #1.4-2.1m
      move_threshold:
        name: Gate 2 Move Threshold
      still_threshold:
        name: Gate 2 Still Threshold
    gate_3:                                         #2.1-2.8m
      move_threshold:
        name: Gate 3 Move Threshold
      still_threshold:
        name: Gate 3 Still Threshold
    gate_4:                                         #2.8-3.5m
      move_threshold:
        name: Gate 4 Move Threshold
      still_threshold:
        name: Gate 4 Still Threshold
    gate_5:                                         #3.5-4.2m
      move_threshold:
        name: Gate 5 Move Threshold
      still_threshold:
        name: Gate 5 Still Threshold
    gate_6:                                         #4.2-4.9m
      move_threshold:
        name: Gate 6 Move Threshold
      still_threshold:
        name: Gate 6 Still Threshold
    gate_7:                                         #4.9-5.6m
      move_threshold:
        name: Gate 7 Move Threshold
      still_threshold:
        name: Gate 7 Still Threshold
    gate_8:                                         #5.6-6.3m
      move_threshold:
        name: Gate 8 Move Threshold
      still_threshold:
        name: Gate 8 Still Threshold
    gate_9:                                         #6.3-7.0m
      move_threshold:
        name: Gate 9 Move Threshold
      still_threshold:
        name: Gate 9 Still Threshold
    gate_10:                                         #7.0-7.7m
      move_threshold:
        name: Gate 10 Move Threshold
      still_threshold:
        name: Gate 10 Still Threshold
    gate_11:                                         #7.7-8.4m
      move_threshold:
        name: Gate 11 Move Threshold
      still_threshold:
        name: Gate 11 Still Threshold
    gate_12:                                         #8.4-9.1m
      move_threshold:
        name: Gate 12 Move Threshold
      still_threshold:
        name: Gate 12 Still Threshold
    gate_13:                                         #9.1-9.8m
      move_threshold:
        name: Gate 13 Move Threshold
      still_threshold:
        name: Gate 13 Still Threshold
    gate_14:                                         #9.8-10.5m
      move_threshold:
        name: Gate 14 Move Threshold
      still_threshold:
        name: Gate 14 Still Threshold
    gate_15:                                         #10.5-11.2m
      move_threshold:
        name: Gate 15 Move Threshold
      still_threshold:
        name: Gate 15 Still Threshold

button:
  - platform: ld2420
    apply_config:
      name: Apply microwave sensor config    # applies configuration (used to set calibrated values)
    factory_reset:
      name: Factory reset microwave sensor   # As the name says
    revert_config:
      name: Abort microwave sensor edits